/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.panels;

import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author ADMIN
 */
public class AddChapterPanel extends javax.swing.JPanel {

    /**
     * Creates new form HistoryPanel
     */
    public AddChapterPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        btnBack = new javax.swing.JLabel();
        lbAddChapter = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listChapter = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1013, 698));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBack.setText("Back");
        btnBack.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel6.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        lbAddChapter.setBackground(new java.awt.Color(0, 204, 102));
        lbAddChapter.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbAddChapter.setForeground(new java.awt.Color(255, 255, 255));
        lbAddChapter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAddChapter.setText("NEW CHAPTER");
        lbAddChapter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbAddChapter.setOpaque(true);
        jPanel6.add(lbAddChapter, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 1011, 40));

        btnCancel.setText("Cancel");
        jPanel6.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 597, 133, 37));

        btnNext.setText("Confirm");
        jPanel6.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 597, 133, 37));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(52, 2));

        listChapter.setBackground(new java.awt.Color(255, 255, 255));
        listChapter.setLayout(new javax.swing.BoxLayout(listChapter, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane2.setViewportView(listChapter);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 47, 999, 544));

        btnAdd.setText("Add");
        jPanel6.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 597, 133, 37));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnCancel() {
        return btnCancel;
    }

    public JButton getBtnNext() {
        return btnNext;
    }

    public JPanel getListChapter() {
        return listChapter;
    }
    
    public void onBtnAdd(ActionListener action) {
        this.btnAdd.addActionListener(action);
    }
    
    public void onBtnBack(MouseAdapter action) {
        this.btnBack.addMouseListener(action);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel btnBack;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnNext;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbAddChapter;
    private javax.swing.JPanel listChapter;
    // End of variables declaration//GEN-END:variables
}
