/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.panels;

import java.awt.event.MouseAdapter;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import other.SetButton;

/**
 *
 * @author ADMIN
 */
public class AllBookPanel extends ParentPanel {

    /**
     * Creates new form AllBookPanel
     */
    public AllBookPanel() {
        initComponents();
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JLabel();
        lbNewUpdate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listAllBook = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1272, 780));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(0, 153, 153));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBack.setText("Back");
        btnBack.setAlignmentY(0.0F);
        btnBack.setOpaque(true);
        btnBack.setPreferredSize(new java.awt.Dimension(60, 50));
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lbNewUpdate.setBackground(new java.awt.Color(0, 153, 153));
        lbNewUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbNewUpdate.setForeground(new java.awt.Color(255, 255, 255));
        lbNewUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNewUpdate.setText("NEW UPDATE");
        lbNewUpdate.setAlignmentY(0.0F);
        lbNewUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbNewUpdate.setOpaque(true);
        lbNewUpdate.setPreferredSize(new java.awt.Dimension(1272, 50));
        add(lbNewUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        listAllBook.setBackground(new java.awt.Color(255, 255, 255));
        listAllBook.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 35, 10, 10));
        listAllBook.setLayout(new java.awt.GridLayout(-1, 6, 10, 20));
        jScrollPane1.setViewportView(listAllBook);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1250, 720));
    }// </editor-fold>//GEN-END:initComponents

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JLabel getLbNewUpdate() {
        return lbNewUpdate;
    }

    public void setLbNewUpdate(JLabel lbNewUpdate) {
        this.lbNewUpdate = lbNewUpdate;
    }

    public JPanel getListAllBook() {
        return listAllBook;
    }

    public void setListAllBook(JPanel listAllBook) {
        this.listAllBook = listAllBook;
    }

    public void onBtnBack(MouseAdapter action) {
        this.btnBack.addMouseListener(new SetButton.SetLabelEffect(btnBack));
        this.btnBack.addMouseListener(action);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbNewUpdate;
    private javax.swing.JPanel listAllBook;
    // End of variables declaration//GEN-END:variables
}
