/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.panels;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author ADMIN
 */
public class BooksPanel extends javax.swing.JPanel {

    /**
     * Creates new form HistoryPanel
     */
    public BooksPanel() {
        initComponents();
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        lbBookManager = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtKeyWords = new javax.swing.JTextField();
        btnSort = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listBook = new javax.swing.JPanel();
        btnAddBook = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1272, 698));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(1272, 698));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        lbBookManager.setBackground(new java.awt.Color(146, 154, 171));
        lbBookManager.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbBookManager.setForeground(new java.awt.Color(255, 255, 255));
        lbBookManager.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBookManager.setText("BOOKS");
        lbBookManager.setAlignmentY(0.0F);
        lbBookManager.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbBookManager.setOpaque(true);
        lbBookManager.setPreferredSize(new java.awt.Dimension(1272, 50));
        jPanel6.add(lbBookManager);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Search bar");

        txtKeyWords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKeyWordsActionPerformed(evt);
            }
        });

        btnSort.setBackground(new java.awt.Color(240, 173, 78));
        btnSort.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSort.setForeground(new java.awt.Color(255, 255, 255));
        btnSort.setText("A->Z");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtKeyWords, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSort)
                .addContainerGap(211, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKeyWords, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSort))
                .addContainerGap())
        );

        jPanel6.add(jPanel3);

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1262, 538));

        listBook.setBackground(new java.awt.Color(255, 255, 255));
        listBook.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 20));
        listBook.setPreferredSize(new java.awt.Dimension(990, 10));
        listBook.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));
        jScrollPane1.setViewportView(listBook);

        jPanel6.add(jScrollPane1);

        btnAddBook.setBackground(new java.awt.Color(240, 173, 78));
        btnAddBook.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAddBook.setForeground(new java.awt.Color(255, 255, 255));
        btnAddBook.setText("Thêm sách");
        btnAddBook.setOpaque(true);
        btnAddBook.setPreferredSize(new java.awt.Dimension(230, 32));
        jPanel6.add(btnAddBook);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtKeyWordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKeyWordsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKeyWordsActionPerformed

    public JTextField getTxtKeyWords() {
        return txtKeyWords;
    }

    public void setTxtKeyWords(JTextField txtKeyWords) {
        this.txtKeyWords = txtKeyWords;
    }

    
    public JPanel getListBook() {
        return listBook;
    }

    public void setListBook(JPanel listBook) {
        this.listBook = listBook;
    }
    
    public void onBtnAddBook(ActionListener action) {
        this.btnAddBook.addActionListener(action);
    }
    
    public void onSortBtnClicked(ActionListener action) {
        this.btnSort.addActionListener(action);
    }
    
    public JButton getBtnSort() {
        return this.btnSort;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBook;
    private javax.swing.JButton btnSort;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBookManager;
    private javax.swing.JPanel listBook;
    private javax.swing.JTextField txtKeyWords;
    // End of variables declaration//GEN-END:variables
}
