/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.items;

import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.JButton;
import javax.swing.JLabel;
import models.ChapterModel;

/**
 *
 * @author ADMIN
 */
public class ChapterItem extends javax.swing.JPanel {

    /**
     * Creates new form ChapterItem
     */
    private ChapterModel chapterModels;
    public ChapterItem(ChapterModel chapterModels) {
        initComponents();
        this.chapterModels = chapterModels;
        this.lbChapter.setText("Chương " + chapterModels.getSerial() + " : " + chapterModels.getTitle());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbChapter = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(32767, 40));
        setPreferredSize(new java.awt.Dimension(980, 50));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        lbChapter.setBackground(new java.awt.Color(255, 255, 255));
        lbChapter.setText("jLabel1");
        lbChapter.setAlignmentY(0.0F);
        lbChapter.setPreferredSize(new java.awt.Dimension(900, 50));
        add(lbChapter);

        btnDelete.setBackground(new java.awt.Color(204, 0, 51));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("x");
        btnDelete.setPreferredSize(new java.awt.Dimension(50, 48));
        add(btnDelete);
    }// </editor-fold>//GEN-END:initComponents
    
    public ChapterModel getChapterModels() {
        return chapterModels;
    }

    public void setChapterModels(ChapterModel chapterModels) {
        this.chapterModels = chapterModels;
    }

    public JButton getBtnDelete() {
        return btnDelete;
    }

    public void setBtnDelete(JButton btnDelete) {
        this.btnDelete = btnDelete;
    }

    public void onBtnDeleteClick(ActionListener action) {
        this.btnDelete.addActionListener(action);
    }

    public JLabel getLbChapter() {
        return lbChapter;
    }

    public void setLbChapter(JLabel lbChapter) {
        this.lbChapter = lbChapter;
    }
    
    public void onLbChapterClick(MouseAdapter action) {
        this.lbChapter.addMouseListener(action);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel lbChapter;
    // End of variables declaration//GEN-END:variables
}
