/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.items;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import javax.swing.JLabel;
import models.DAO.ReviewDAO;
import models.ReviewModel;
import models.entityPK.ReviewPK;
import other.SetButton;
import static utils.formatDate.formatDate;

/**
 *
 * @author ADMIN
 */
public class CommentItem extends javax.swing.JPanel {

    /**
     * Creates new form ChapterItem
     */
    private ReviewModel reviewModels;

    public CommentItem(ReviewModel reviewModels) throws SQLException, ParseException {
        initComponents();
        this.reviewModels = reviewModels;
        this.txtComment.setText("" + ReviewDAO.getInstance().getUserNameFromReviewPK(new ReviewPK( reviewModels.getUser_id(), reviewModels.getBook_id()))
                + " : " + reviewModels.getComment());
         DecimalFormat decimalFormat = new DecimalFormat("#.#");
        String rating = decimalFormat.format(reviewModels.getRating());
        this.txtRate.setText("Rating: " + rating + "/" + 5);
        String formatDate = formatDate("" + reviewModels.getReviewDate());
        this.txtDate.setText(formatDate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtComment = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        txtRate = new javax.swing.JLabel();
        btnDelete = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(32767, 40));
        setPreferredSize(new java.awt.Dimension(1252, 50));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        txtComment.setBackground(new java.awt.Color(255, 255, 255));
        txtComment.setText("jLabel1");
        txtComment.setAlignmentY(0.0F);
        txtComment.setPreferredSize(new java.awt.Dimension(940, 50));
        add(txtComment);

        txtDate.setText("date");
        add(txtDate);

        txtRate.setText("jLabel1");
        txtRate.setPreferredSize(new java.awt.Dimension(145, 50));
        add(txtRate);

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_icon.png"))); // NOI18N
        btnDelete.setOpaque(true);
        btnDelete.setPreferredSize(new java.awt.Dimension(50, 48));
        add(btnDelete);
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getBtnDelete() {
        return btnDelete;
    }

    public void setBtnDelete(JLabel btnDelete) {
        this.btnDelete = btnDelete;
    }

    public void onBtnDeleteClick(MouseAdapter action) {
        this.btnDelete.addMouseListener(new SetButton.SetLabelEffectB(this.btnDelete));
        this.btnDelete.addMouseListener(action);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnDelete;
    private javax.swing.JLabel txtComment;
    private javax.swing.JLabel txtDate;
    private javax.swing.JLabel txtRate;
    // End of variables declaration//GEN-END:variables
}
