package views;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseListener;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;

public class LoginForm extends javax.swing.JFrame {
    public LoginForm() {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/icon_app.jpg"));  
        this.setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        heading = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        userNameInput = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        registerBtn = new javax.swing.JLabel();
        passwordInput = new javax.swing.JPasswordField();
        userNameErrorMess = new javax.swing.JLabel();
        passwordErrorMess = new javax.swing.JLabel();
        showPasswordBtn = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        heading.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heading.setText("Login");
        getContentPane().add(heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 23, 290, 38));

        userNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userNameLabel.setLabelFor(userNameInput);
        userNameLabel.setText("Username");
        getContentPane().add(userNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 79, 290, -1));

        userNameInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(userNameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 105, 290, 42));

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordLabel.setLabelFor(passwordInput);
        passwordLabel.setText("Password");
        getContentPane().add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 164, 290, 24));

        loginBtn.setBackground(new java.awt.Color(0, 0, 0));
        loginBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Login");
        getContentPane().add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 382, 290, 43));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Do not have an account ?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 437, -1, -1));

        registerBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(0, 51, 255));
        registerBtn.setText("Sign up");
        registerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 437, -1, -1));
        getContentPane().add(passwordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 194, 290, 42));

        userNameErrorMess.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(userNameErrorMess, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 152, 290, -1));

        passwordErrorMess.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(passwordErrorMess, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 268, 290, -1));

        showPasswordBtn.setBackground(new java.awt.Color(255, 255, 255));
        showPasswordBtn.setText("Show password");
        showPasswordBtn.setOpaque(true);
        getContentPane().add(showPasswordBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 242, 290, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getPasswordErrorMess() {
        return passwordErrorMess;
    }

    public JPasswordField getPasswordInput() {
        return passwordInput;
    }

    public JCheckBox getShowPasswordBtn() {
        return showPasswordBtn;
    }

    public JLabel getUserNameErrorMess() {
        return userNameErrorMess;
    }

    public JTextField getUserNameInput() {
        return userNameInput;
    }

    
    public void onLogin(ActionListener action) {
        this.loginBtn.addActionListener(action);
    }
    
    public void onRegisterLinkClicked(MouseAdapter action) {
        this.registerBtn.addMouseListener(action);
    }
    
    public void onToggleShowPassword(ActionListener action) {
        this.showPasswordBtn.addActionListener(action);
    }
        
    public void start() {
        java.awt.EventQueue.invokeLater(() -> {
            pack();
            setLocationRelativeTo(null);
            setResizable(false);
            setTitle("Wibu Forever (hay gì gì đó)");
            setDefaultCloseOperation(EXIT_ON_CLOSE);
            setVisible(true);
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel heading;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel passwordErrorMess;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel registerBtn;
    private javax.swing.JCheckBox showPasswordBtn;
    private javax.swing.JLabel userNameErrorMess;
    private javax.swing.JTextField userNameInput;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
