/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controller.panel.MainPanelController;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.accessibility.AccessibleContext;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import models.UserModel;
import other.SetButton;
import views.items.ButtonItem;
import views.panels.InforPanel;
import views.panels.ParentPanel;

/**
 *
 * @author ADMIN
 */
public class MainView extends javax.swing.JFrame {
    UserModel userModels;
    
    public MainView(UserModel userModels) {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/icon_app.jpg"));  
        this.setIconImage(icon);
        Dimension DimMax = Toolkit.getDefaultToolkit().getScreenSize();
        System.out.println(DimMax.getHeight());
        setPreferredSize(new Dimension(DimMax.width, DimMax.height - 40));
//
//setExtendedState(JFrame.MAXIMIZED_BOTH);
        //setExtendedState(JFrame.MAXIMIZED_BOTH);     
        setResizable(false);
        this.userModels = userModels;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbAvatar = new javax.swing.JLabel();
        lbUsername = new javax.swing.JLabel();
        groupBtn = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 800));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 200));

        lbAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/avatar_default.jpg"))); // NOI18N
        lbAvatar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 5));
        lbAvatar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbAvatar.setPreferredSize(new java.awt.Dimension(157, 157));
        jPanel2.add(lbAvatar);

        lbUsername.setBackground(new java.awt.Color(0, 153, 153));
        lbUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbUsername.setForeground(new java.awt.Color(255, 255, 255));
        lbUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbUsername.setText("username");
        lbUsername.setOpaque(true);
        lbUsername.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel2.add(lbUsername);

        jPanel1.add(jPanel2);

        groupBtn.setBackground(new java.awt.Color(0, 153, 153));
        groupBtn.setPreferredSize(new java.awt.Dimension(250, 400));
        groupBtn.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));
        jPanel1.add(groupBtn);

        jPanel7.add(jPanel1);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setAlignmentX(0.0F);
        mainPanel.setAlignmentY(0.0F);
        mainPanel.setPreferredSize(new java.awt.Dimension(1272, 800));
        mainPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));
        jPanel7.add(mainPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void setUserModel(UserModel user) {
        this.userModels = user;
    }
    
    public UserModel getUserModels() {
        return userModels;
    }

    public JPanel getjPanel3() {
        return mainPanel;
    }

    public void setMainPanel(ParentPanel panel) {
        for(int i = 0; i < this.groupBtn.getComponentCount(); i++){
            ButtonItem a = (ButtonItem) this.groupBtn.getComponent(i);
            SetButton.SetBtnMain j = (SetButton.SetBtnMain) a.getEvents();
            j.setActiveWithPanel(panel.getName());
        }
        this.mainPanel.removeAll();
        this.mainPanel.add(panel);  
        this.mainPanel.revalidate();
        this.mainPanel.repaint();
    }

    public JLabel getLbAvatar() {
        return lbAvatar;
    }

    public JLabel getLbUsername() {
        return lbUsername;
    }

    public JPanel getGroupBtn() {
        return groupBtn;
    }
    
    

    /**
     * @param args the command line arguments
     */
    public void start() {
        java.awt.EventQueue.invokeLater(() -> {
            pack();
            setLocationRelativeTo(null);
            setDefaultCloseOperation(EXIT_ON_CLOSE);
            setTitle("No books no life");
            setVisible(true);
        });
    }

    //Event

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel groupBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lbAvatar;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
