/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controller.panel.MainPanelController;
import java.awt.event.ActionListener;
import javax.accessibility.AccessibleContext;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import models.UserModel;

/**
 *
 * @author ADMIN
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    UserModel userModels;
    public MainView(UserModel userModels) {
        initComponents();
        this.userModels = userModels;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbAvatar = new javax.swing.JLabel();
        lbUsername = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnMain = new javax.swing.JButton();
        btnInFor = new javax.swing.JButton();
        btnLibrary = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnBookManager = new javax.swing.JButton();
        btnUserManager = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 255));
        setResizable(false);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(157, 718));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(157, 158));

        lbAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/avatar_default.jpg"))); // NOI18N
        lbAvatar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbAvatar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbAvatar.setPreferredSize(new java.awt.Dimension(157, 157));

        lbUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbUsername.setText("username");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lbAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(143, 389));

        btnMain.setBackground(new java.awt.Color(204, 0, 51));
        btnMain.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnMain.setForeground(new java.awt.Color(255, 255, 255));
        btnMain.setText("Màn hình chính");
        btnMain.setPreferredSize(new java.awt.Dimension(143, 43));
        jPanel4.add(btnMain);

        btnInFor.setBackground(new java.awt.Color(204, 0, 51));
        btnInFor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnInFor.setForeground(new java.awt.Color(255, 255, 255));
        btnInFor.setText("Thông tin tài khoản");
        btnInFor.setPreferredSize(new java.awt.Dimension(143, 43));
        jPanel4.add(btnInFor);

        btnLibrary.setBackground(new java.awt.Color(204, 0, 51));
        btnLibrary.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnLibrary.setForeground(new java.awt.Color(255, 255, 255));
        btnLibrary.setText("Thư viện của bạn");
        btnLibrary.setPreferredSize(new java.awt.Dimension(143, 43));
        jPanel4.add(btnLibrary);

        btnHistory.setBackground(new java.awt.Color(204, 0, 51));
        btnHistory.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnHistory.setForeground(new java.awt.Color(255, 255, 255));
        btnHistory.setText("Lịch sử đọc");
        btnHistory.setPreferredSize(new java.awt.Dimension(143, 43));
        jPanel4.add(btnHistory);

        btnSearch.setBackground(new java.awt.Color(204, 0, 51));
        btnSearch.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Tìm kiếm nâng cao");
        btnSearch.setPreferredSize(new java.awt.Dimension(143, 43));
        jPanel4.add(btnSearch);

        btnBookManager.setBackground(new java.awt.Color(204, 0, 51));
        btnBookManager.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnBookManager.setForeground(new java.awt.Color(255, 255, 255));
        btnBookManager.setText("Quản lý sách");
        btnBookManager.setPreferredSize(new java.awt.Dimension(143, 43));
        jPanel4.add(btnBookManager);

        btnUserManager.setBackground(new java.awt.Color(204, 0, 51));
        btnUserManager.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnUserManager.setForeground(new java.awt.Color(255, 255, 255));
        btnUserManager.setText("Quản lý người dùng");
        btnUserManager.setPreferredSize(new java.awt.Dimension(143, 43));
        jPanel4.add(btnUserManager);

        btnLogOut.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(204, 0, 51));
        btnLogOut.setText("Đăng xuất");
        btnLogOut.setBorder(null);
        btnLogOut.setBorderPainted(false);
        btnLogOut.setOpaque(true);
        btnLogOut.setPreferredSize(new java.awt.Dimension(143, 43));
        jPanel4.add(btnLogOut);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnBack.setText("Quay lại");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1019, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(147, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public UserModel getUserModels() {
        return userModels;
    }

    public JButton getBtnHistory() {
        return btnHistory;
    }

    public JButton getBtnInFor() {
        return btnInFor;
    }

    public JButton getBtnLibrary() {
        return btnLibrary;
    }

    public JButton getBtnLogOut() {
        return btnLogOut;
    }

    public JButton getBtnMain() {
        return btnMain;
    }

    public JButton getBtnSearch() {
        return btnSearch;
    }

    public JPanel getjPanel3() {
        return mainPanel;
    }

    public void setMainPanel(JPanel panel) {
        this.mainPanel.removeAll();
        this.mainPanel.add(panel);  
        this.mainPanel.revalidate();
        this.mainPanel.repaint();
    }

    public JLabel getLbAvatar() {
        return lbAvatar;
    }

    public JLabel getLbUsername() {
        return lbUsername;
    }

    public JButton getBtnBookManager() {
        return btnBookManager;
    }

    public JButton getBtnUserManager() {
        return btnUserManager;
    }

    /**
     * @param args the command line arguments
     */
    public void start() {
        java.awt.EventQueue.invokeLater(() -> {
            pack();
            setLocationRelativeTo(null);
            setDefaultCloseOperation(EXIT_ON_CLOSE);
            setTitle("Main view");
            setVisible(true);
        });
    }

    //Event
    public void onBtnInfor(ActionListener action) {
        this.btnInFor.addActionListener(action);
    }
    
    public void onBtnHistory(ActionListener action) {
        this.btnHistory.addActionListener(action);
    }
    
    public void onBtnSearch(ActionListener action) {
        this.btnSearch.addActionListener(action);
    }
    
    public void onBtnLibrary(ActionListener action) {
        this.btnLibrary.addActionListener(action);
    }

    public void onBtnMain(ActionListener action) {
        this.btnMain.addActionListener(action);
    }
    
    public void onBtnLogOut(ActionListener action) {
        this.btnLogOut.addActionListener(action);
    }
    
    public void onBtnBookManager(ActionListener action) {
        this.btnBookManager.addActionListener(action);
    }
    
    public void onBtnUserManager(ActionListener action) {
        this.btnUserManager.addActionListener(action);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBookManager;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnInFor;
    private javax.swing.JButton btnLibrary;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnMain;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUserManager;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lbAvatar;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
