CREATE DEFINER = CURRENT_USER TRIGGER `project1`.`userinfo_BEFORE_INSERT` BEFORE INSERT ON `userinfo` FOR EACH ROW
BEGIN
	IF CHAR_LENGTH(NEW.user_phoneNumber) != 10 THEN 
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'PHONE NUMBER MUST BE EQUAL TO 10 CHARACTERS';
	END IF;
END
